# Generated by Django 5.1.1 on 2026-03-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_image_user_city'),
        ('accounts', '0004_remove_user_is_email_verified_and_more'),
    ]

    operations = [
    ]
