# Generated by Django 6.0.3 on 2026-03-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_loyalty_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyrecord',
            name='confirmed_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of confirmed (non-free) bookings by this user at this ground.'),
        ),
    ]
