# Generated by Django 6.0.3 on 2026-04-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_payment_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_free_booking',
            field=models.BooleanField(default=False, help_text='True for loyalty-free or rescheduling-token bookings. Does NOT earn loyalty points.', verbose_name='Free Booking'),
        ),
        migrations.AlterField(
            model_name='loyaltyrecord',
            name='confirmed_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of confirmed PAID (non-free) bookings.'),
        ),
        migrations.AlterField(
            model_name='loyaltyrecord',
            name='free_bookings_earned',
            field=models.PositiveIntegerField(default=0, help_text='Total free bookings earned (every 5 paid confirmed bookings).'),
        ),
    ]
