# Generated by Django 5.1.1 on 2026-03-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground',
            name='ground_size',
            field=models.CharField(choices=[('5', '5-a-side'), ('6', '6-a-side'), ('7', '7-a-side')], default='5', max_length=2, verbose_name='Ground Size (players per side)'),
        ),
        migrations.AddField(
            model_name='ground',
            name='ground_type',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='outdoor', max_length=10, verbose_name='Ground Type'),
        ),
    ]
