# Generated by Django 6.0.3 on 2026-04-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0006_blocked_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedslot',
            name='block_type',
            field=models.CharField(choices=[('date', 'Specific Date'), ('recurring', 'Recurring Day')], default='date', max_length=10),
        ),
        migrations.AlterField(
            model_name='blockedslot',
            name='blocked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockedslot',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='0=Monday…6=Sunday', null=True),
        ),
        migrations.AlterField(
            model_name='blockedslot',
            name='end_hour',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blockedslot',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blockedslot',
            name='start_hour',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ground',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='ground',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='peakpricingrule',
            name='day_of_week',
            field=models.IntegerField(choices=[(-1, 'All Days'), (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=-1, help_text='0=Monday … 6=Sunday. Use -1 for all days.'),
        ),
        migrations.AlterField(
            model_name='peakpricingrule',
            name='end_hour',
            field=models.PositiveSmallIntegerField(help_text='Peak period end hour (0–23), exclusive'),
        ),
        migrations.AlterField(
            model_name='peakpricingrule',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, help_text='Price per hour during this period', max_digits=10),
        ),
        migrations.AlterField(
            model_name='peakpricingrule',
            name='start_hour',
            field=models.PositiveSmallIntegerField(help_text='Peak period start hour (0–23)'),
        ),
    ]
