# Generated by Django 6.0.3 on 2026-04-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounds', '0008_peakpricingrule_rule_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peakpricingrule',
            options={'ordering': ['rule_type', 'start_hour'], 'verbose_name': 'Pricing Rule', 'verbose_name_plural': 'Pricing Rules'},
        ),
        migrations.AlterField(
            model_name='peakpricingrule',
            name='end_hour',
            field=models.PositiveSmallIntegerField(help_text='End hour (0–23), exclusive'),
        ),
        migrations.AlterField(
            model_name='peakpricingrule',
            name='label',
            field=models.CharField(default='Peak Hours', help_text='e.g. "Evening Peak", "Morning Discount"', max_length=100),
        ),
        migrations.AlterField(
            model_name='peakpricingrule',
            name='start_hour',
            field=models.PositiveSmallIntegerField(help_text='Start hour (0–23)'),
        ),
    ]
