# Generated by Django 6.0.1 on 2026-01-15 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futsal',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='futsalowner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('player', 'Player'), ('owner', 'Owner')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Futsal',
        ),
        migrations.DeleteModel(
            name='FutsalOwner',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
